# Configuration options and their default values:
#
#rbac:
#  configLocation: rbac.yaml
#  springRoles: true

# In order to use default userdetailsService of Spring Boot: 
# - remove exclusion of UserDetailsServiceAutoConfiguration in Application.java 
# - cleanup SecurityConfiguration#configure(AuthenticationManagerBuilder): replace content of method with "auth.userDetailsService(rbacUserDetailService);"
# - uncomment default roles below
#  
#spring.security.user.roles: [admin, user, none]

spring.mvc.favicon.enabled: true
spring.messages.encoding: UTF-8
server.tomcat.uri-encoding: UTF-8
spring.http.encoding.charset: UTF-8
