name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11

    - name: Build with Maven
      run: mvn -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -f rbac-services -Pcodecoverage,release clean install
      
    - name: Codecov
      uses: codecov/codecov-action@v1.0.4
      with:
        token: ${{ secrets.codecov_token }}
