name: Deploy artifacts

on:
  push:
    tags:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11

    - name: Build with Maven
      run: mvn -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -DskipTests=true -f rbac-services -Prelease clean install

    - name: Deploy to Github Packages
      run: mvn -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -Dmaven.wagon.http.pool=false -DskipTests=true -Dgithub.user=${{ secrets.github_user }} -Dgithub.password=${{ secrets.github_token }} -f rbac-services -s rbac-services/settings.xml -Prelease deploy 
